import { getPages } from "@/sanity/sanity-utils";
import "../globals.css";
import Link from "next/link";

export const revalidate = 0;

export const metadata = {
  title: "George Lil World",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-6xl mx-auto py-10, father">
        <header className="mx-5 flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
            次元封面
          </Link>
          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="mx-5 py-10">{children}</main>
      </body>
    </html>
  );
}
